### ISSUE TITLE
SDBN: Found the game

### ISSUE THREAD

**Issue by supahas** [diva-eng/sega-nu#1]
Heya there, not really an issue but I'd figure I'll point it out in case you didn't find out already. The keychip regarding game ID "SDBN" is a game called "え～でる すなば"/"E-deru Sandbox". The game is indeed on the Nu SX platform, but there's not a whole lot of information surrounding it from what I can see. Only thing I found was this: (https://www.youtube.com/watch?v=lKR4BDuwZlU). I suppose, given it's a Nu game, we can assume it follows the same security and whatnot as DIVA.

Again, apologies for the "fake issue", but I figured you'd probably want to know this in case you haven't already.

**Comment by r1cebank** [comment]
Hey, thank you for pointing it out, Yes the two different key chips are listed in the documentation. The SDBN was cheap enough to obtain for me to start reverse engineering on it so I don't have to do it on the real DIVA keychip as its quite rare.

The PCB for the two keychips are exactly the same and the Nu SX keychip can be recognized on the Nu platform as well.

**Comment by supahas** [comment]
Ah that's cool, can't say I didn't expect it. Would it be alright to assume the same logic for the Nu 1.1 as well? I've seen more than one guy install and boot SDBT on a Nu 1.0. Would be crazy if all three were interchangeable.

**Comment by r1cebank** [comment]
I do not have an Nu 1.1 so I couldn't really test, but based on the manual I had for the Nu 1.1 and drivers I would say they work the same. These keychips are just regular usb devices that would work anywhere via USB, given if you have the driver for it.
