### ISSUE TITLE
Contact information

### ISSUE THREAD

**Issue by jota2rz** [diva-eng/sega-nu#6]
@r1cebank How may I contact you in private? The e-mail at your website is not working.

**Comment by biggestsonicfan** [comment]
This is unrelated to the sega-nu repository. The website lists the email as `rbnk@elica.io` however the personal github page of r1cebank lists an email as `me@r1ce.net`, which seems to be correct as elica.io does not exist and r1ce.net is their website. Please consider exploring these avenues before filing issues unrelated to github projects.

If the information is regarding the sega-nu project, I suggest you elaborate a bit on why a private inquiry is necessary, such as documentation or non-public files related to the project.

**Comment by jota2rz** [comment]
@biggestsonicfan This is related to the repository, I will try to contact him over that e-mail, thank you.

**Comment by r1cebank** [comment]
Sorry about the late reply, that was an old domain that got expired.

**Comment by jota2rz** [comment]
> Sorry about the late reply, that was an old domain that got expired. Will update my website later today.

E-mail sent.
